# Generated by Django 4.1 on 2022-11-10 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_category_alter_news_options_alter_news_content_and_more'),
        ('news', '0003_category_news_category'),
    ]

    operations = [
    ]
